spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            CircuitBreaker:
              - args:
                    - name: order-service
                    - fallbackuri  : forward:/orderFallback
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filter:
            CircuitBreaker:
              - args:
                  - name: payment-service
                  - fallbackuri: forward:/paymentFallback
server:
  port: 8989

debug: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000